import{a as L,S as w,i}from"./assets/vendor-xwsNXkQR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const E="https://pixabay.com/api/",v="52809699-ccc5c93f5d687b44e4326bc01",P=15;async function h(r,e=1){const o=`${E}?key=${v}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&PRE_PAGE=${P}`;try{return(await L.get(o)).data}catch{throw new Error("Failed to fetch images")}}const c=document.querySelector(".gallery"),a=document.querySelector(".loader"),l=document.querySelector(".load_more_button");a&&a.classList.add("hidden");const f=new w(".gallery a",{captionsData:"alt",captionDelay:250});function A(r){return r.map(e=>`
        <li class="gallery-item">
          <a class="gallery-image" href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" />
          </a>
          <div class="info">
            <p ><b>Likes:</b> ${e.likes}</p>
            <p ><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </li>
      `).join("")}function y(r){if(!Array.isArray(r)||r.length===0||!c)return;const e=A(r);c.insertAdjacentHTML("beforeend",e),f.refresh()}function S(){c&&(c.innerHTML="",f.refresh())}function $(){a&&a.classList.remove("hidden")}function m(){a&&a.classList.add("hidden")}function g(){l&&l.classList.remove("hidden")}function q(){l&&l.classList.add("hidden")}const p=document.querySelector(".form"),b=p.elements["search-text"];let d=1;const B=document.querySelector(".load_more_button");B.addEventListener("click",I);p.addEventListener("submit",async r=>{r.preventDefault(),d=1;const e=b.value.trim();if(!e){i.warning({title:"Warning",message:"Please enter a search term!"});return}S(),$();try{const o=await h(e,d);if(!o||!Array.isArray(o.hits))throw new Error("Bad response shape from API");if(o.hits.length===0){i.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(o.hits),g()}catch(o){console.error(o),i.error({title:"Error",message:"Network error or API failed. Try again later."})}finally{m()}});async function I(){const r=b.value.trim();d=1;try{const e=await h(r,d);y(e.hits);const o=e.hits.length,s=e.totalHits;o>=s?g():(q(),i.info({title:"End",message:"We're sorry, but you've reached the end of search results."})),f.refresh()}catch{}finally{m()}}function M(){const r=document.querySelector(".gallery .photo-card");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,left:0,behavior:"smooth"})}M();
//# sourceMappingURL=index.js.map
