import{a as $,S as q,i as a}from"./assets/vendor-xwsNXkQR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const g of n.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&d(g)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function d(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const B="https://pixabay.com/api/",I="52809699-ccc5c93f5d687b44e4326bc01",M=15;async function w(e,r=1){const o=`${B}?key=${I}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${M}`;try{return(await $.get(o)).data}catch{throw new Error("Failed to fetch images")}}const i=document.querySelector(".gallery"),l=document.querySelector(".loader"),h=document.querySelector(".load_more_button");l&&l.classList.add("hidden");const b=new q(".gallery a",{captionsData:"alt",captionDelay:250});function L(e){return e.map(r=>`
        <li class="gallery-item">
          <a class="gallery-image" href="${r.largeImageURL}">
            <img src="${r.webformatURL}" alt="${r.tags}" />
          </a>
          <div class="info">
            <p ><b>Likes:</b> ${r.likes}</p>
            <p ><b>Views:</b> ${r.views}</p>
            <p><b>Comments:</b> ${r.comments}</p>
            <p><b>Downloads:</b> ${r.downloads}</p>
          </div>
        </li>
      `).join("")}function P(e){if(!Array.isArray(e)||e.length===0||!i)return;const r=L(e);i.insertAdjacentHTML("beforeend",r),b.refresh()}function _(e){if(!Array.isArray(e)||e.length===0||!i)return;const r=L(e);i.insertAdjacentHTML("beforeend",r),b.refresh()}function T(){i&&(i.innerHTML="",b.refresh())}function A(){l&&l.classList.remove("hidden")}function E(){l&&l.classList.add("hidden")}function v(){h&&h.classList.remove("hidden")}function c(){h&&h.classList.add("hidden")}const S=document.querySelector(".form"),N=S.elements["search-text"],p=document.querySelector(".load_more_button");let y=1,m="",u=0,f=0,s=!1;p.addEventListener("click",x);S.addEventListener("submit",O);async function O(e){if(e.preventDefault(),s)return;const r=N.value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a search term!"});return}y=1,m=r,u=0,f=0,T(),c(),A(),s=!0;try{const o=await w(m,y);if(!o||!Array.isArray(o.hits))throw new Error("Bad response shape from API");if(o.hits.length===0){a.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!"});return}P(o.hits),u=o.hits.length,f=Number(o.totalHits)||0,u<f?v():(c(),a.info({title:"End",message:"That's all for this query."}))}catch(o){console.error(o),a.error({title:"Error",message:"Network error or API failed. Try again later."})}finally{E(),s=!1}}async function x(){if(!s){s=!0,y+=1,c(),p.disabled=!0,A();try{const e=await w(m,y);if(!e||!Array.isArray(e.hits))throw new Error("Bad response shape from API (loadMore)");if(e.hits.length===0){c(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."});return}_(e.hits),u+=e.hits.length,u>=f?(c(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):v(),C()}catch(e){console.error(e),a.error({title:"Error",message:"Network error or API failed. Try again later."})}finally{E(),p.disabled=!1,s=!1}}}function C(){const e=document.querySelector(".gallery li");if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
