import{a as q,S as B,i as s}from"./assets/vendor-xwsNXkQR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const m of n.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&d(m)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function d(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const I="https://pixabay.com/api/",P="52809699-ccc5c93f5d687b44e4326bc01",M=15;async function w(e,r=1){const o=`${I}?key=${P}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${M}`;try{return(await q.get(o)).data}catch{throw new Error("Failed to fetch images")}}const f=document.querySelector(".gallery"),i=document.querySelector(".loader"),h=document.querySelector(".load_more_button");i&&i.classList.add("hidden");const g=new B(".gallery a",{captionsData:"alt",captionDelay:250});function _(e){return e.map(r=>`
        <li class="gallery-item">
          <a class="gallery-image" href="${r.largeImageURL}">
            <img src="${r.webformatURL}" alt="${r.tags}" />
          </a>
          <div class="info">
            <p ><b>Likes:</b> ${r.likes}</p>
            <p ><b>Views:</b> ${r.views}</p>
            <p><b>Comments:</b> ${r.comments}</p>
            <p><b>Downloads:</b> ${r.downloads}</p>
          </div>
        </li>
      `).join("")}function L(e){if(!Array.isArray(e)||e.length===0||!f)return;const r=_(e);f.insertAdjacentHTML("beforeend",r),g.refresh()}function N(){f&&(f.innerHTML="",g.refresh())}function E(){i&&i.classList.remove("hidden")}function v(){i&&i.classList.add("hidden")}function A(){h&&h.classList.remove("hidden")}function l(){h&&h.classList.add("hidden")}const S=document.querySelector(".form"),O=S.elements["search-text"],p=document.querySelector(".load_more_button");let y=1,b="",c=0,u=0,a=!1;p.addEventListener("click",x);S.addEventListener("submit",T);async function T(e){if(e.preventDefault(),a)return;const r=O.value.trim();if(!r){s.warning({title:"Warning",message:"Please enter a search term!"});return}y=1,b=r,c=0,u=0,N(),l(),E(),a=!0;try{const o=await w(b,y);if(!o||!Array.isArray(o.hits))throw new Error("Bad response shape from API");if(o.hits.length===0){s.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!"});return}L(o.hits),g.refresh(),c=o.hits.length,u=Number(o.totalHits)||0,c<=u?A():(l(),s.info({title:"End",message:"That's all for this query."})),$()}catch(o){console.error(o),s.error({title:"Error",message:"Network error or API failed. Try again later."})}finally{v(),a=!1}}async function x(){if(!a){a=!0,y+=1,l(),p.disabled=!0,E();try{const e=await w(b,y);if(!e||!Array.isArray(e.hits))throw new Error("Bad response shape from API (loadMore)");if(e.hits.length===0){l(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results."});return}L(e.hits),g.refresh(),c+=e.hits.length,c>=u?(l(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):A(),$()}catch(e){console.error(e),s.error({title:"Error",message:"Network error or API failed. Try again later."})}finally{v(),p.disabled=!1,a=!1}}}function $(){const e=document.querySelector(".gallery .photo-card");if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
